- name: Add repos key
  apt_key: id={{ item }} keyserver=hkp://p80.pool.sks-keyservers.net:80 
  with_items:
    - "58118E89F3A912897C070ADBF76221572C52609D"
  when: package_source == 'repository'

- name: update cache system
  apt: update_cache=yes

- name: upgrade system
  apt: upgrade=yes
  when: do_upgrade == "yes" 

- name: install required packages (apt-transport-https,ca-certificates)
  apt: name={{ item }} state=present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "git"
    - "aufs-tools"
    - "cgroup-lite"
    - "cgroup-bin" 

- name: create new repo file (/etc/apt/sources.list.d/docker.list)
  file: path=/etc/apt/sources.list.d/docker.list state=touch

- name: add repo to repofile if ubuntu14.04 
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-trusty main" dest="/etc/apt/sources.list.d/docker.list"
  when: (ansible_distribution_release ==  "trusty")

- name: add repo to repofile if ubuntu16.04
  copy: content="deb https://apt.dockerproject.org/repo ubuntu-xenial main" dest="/etc/apt/sources.list.d/docker.list"
  when: (ansible_distribution_release == "xenial")

- name: update cache once again
  apt: update_cache=yes

- name: purge previous lxc-docker version
  apt: pkg=lxc-docker state=absent purge=yes force=yes

- name: install linux-image-extra 
  shell: apt-get install -y linux-image-extra-$(uname -r) linux-image-extra-virtual

- name: install docker engine
  apt: pkg=docker-engine state=present

- name: adding users to docker group
  shell: usermod -aG docker {{ item }}
  with_items:
    - "{{ group }}"

- name: run docker engine
  service: name=docker state=started enabled=yes
